name: EPvP
version: '1.2.0'
main: de.paulsenik.mc.epvp.EPvP
api-version: 1.19
authors: [ Paulsenik ]
description: Extends the vanilla pvp experience in a new way
website: https://paulsenik.de/

commands:
  epvp:
    description: Open Settings for "EPvP"
    usage: /<command> to open manual
    permission: op
  howto-epvp:
    description: Open Manual for "EPvP"
    usage: /<command> to open manual